### ISSUE TITLE
Volumes still not working

### ISSUE THREAD

**Issue by GodGinrai** [tiangolo/babun-docker#16]
I let babun-docker set up the directory for my drives in VirtualBox, but when I attach the directory via `docker run -v $(pwd):/some/directory -it image` I still see an empty directory in `/some/directory` in my image.  The drive seems to be properly listed in VirtualBox as a shared folder, so I'm not sure what's going wrong. :\

**Comment by tiangolo** [comment]
@GodGinrai: **babun-docker** will share and mount the volumes when it starts the Docker Machine VM (in VirtualBox). But if the VM was already started, it won't try to share and mount the volumes, so, make sure you don't turn the VM on before using Docker through **docker-babun**.

A simple way to turn the VM on with **docker-babun** is to run `docker ps`. It will do all the necessary steps to share the volumes with VirtualBox, turn the VM on and mount the volumes inside of it.

If the above isn't causing the problem, first, make sure that the volumes are correctly shared and mounted inside the VM (before running a container).
- SSH into your VM: `docker-machine ssh default`
- Go to the directory with your code (the one you were calling with `$(pwd)`). It would be somewhere inside `/cygdrive`, like `/cygdrive/c/users/nickname/dockerproject`. So, for example: `cd /cygdrive/c/users/nickname/dockerproject`. 
- Check that the contents are there: `ls`

**Comment by GodGinrai** [comment]
That's actually how I started the VM.  I've confirmed with `docker-machine ssh` that the files are there.  I'm starting to think it is because of the path that is being passed.  I was trying to use a folder that is under my cygwin home directory, and I believe that the `/home/user/dir` that is being passed by `pwd` does not work since it is not using the path within `/cygdrive`.

Oddly enough, the directory exists when I `docker-machine ssh` from that directory, but it has no files in it.  Any ideas on how to fix this?  Or will I just have to move the files out of my homedir?

**Comment by tiangolo** [comment]
@GodGinrai: Hmmm, the program is made so that you can use any directory anywhere in your hard drives without having to change anything. 

But the directories inside your _HOME_ are a special case, as Babun (Cygwin) will map them directly as `/home/user/dir`, while they will actually be inside a directory inside your Babun (Cygwin) installation, somewhere like `C:\Users\user\.babun\cygwin\home\user`. So, that directory would end up appearing in `/cygdrive/c/users/user/.babun/cygwin/home/user/dir`. But as Babun interprets `$(pwd)` as `/home/user/dir`, it will never be found.

The easiest thing I can suggest you is moving your code to somewhere in your hard drives, anywhere outside the Babun (Cygwin) installation directory. I would also recommend you doing so as otherwise your code would be inside a hidden directory of the installation under your Windows "home". And if you decided to replace your Babun installation you could lose all your code.

**Comment by GodGinrai** [comment]
Alright, I will move the code.  Thanks for the help.

**Comment by tiangolo** [comment]
You're welcome!
