### ISSUE TITLE
Docker exec isn't working for machines run outside VirtualBox

### ISSUE THREAD

**Issue by StalkAlex** [tiangolo/babun-docker#28]
Problem is connected with docker machines run on other host like vSphere. 
```bash
  app git:(develop) ✗ docker-machine ls
NAME      ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER        ERRORS
default   -        virtualbox      Stopped                                      Unknown
vm        *        vmwarevsphere   Running   tcp://192.168.1.213:2376           v17.04.0-ce
```
As it could be seen I have vm in started state. Then I wanted to `docker exec` one of my container.

 ```bash
Error response from daemon: No such container: app_php_1
```
By docker tutorial I need to do next actions.

```bash
➜  app git:(develop) ✗ docker-machine env vm
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.1.213:2376"
export DOCKER_CERT_PATH="C:\Users\name\.docker\machine\machines\vm"
export DOCKER_MACHINE_NAME="vm"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env vm)
```
It suggested to run command above. After that everything would work in standard docker terminal.
I ran this command, but had to modify path I thought
```bash
 eval $("/cygdrive/c/Program Files/Docker Toolbox/docker-machine.exe" env vm)
```
At the end `docker exec` failed
```bash
➜  app git:(develop) ✗ docker exec -it app_php_1 bash
time="2017-04-14T16:47:52+05:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
-- babun-docker: Using winpty
Could not start '"C:/Program Files/Git/cygdrive/c/Program Files/Docker Toolbox/docker" exec -it app_php_1 bash': Не удается найти указанный файл. (error 0x2)
```
It was not able to find specified path, which seemed incorrect.

**Comment by tiangolo** [comment]
Did you try running that without specifying the path? 

As in:

```bash
eval "$(docker-machine env vm --shell bash)"

```

**Comment by StalkAlex** [comment]
@tiangolo  just tried, it's still the same error.

**Comment by tiangolo** [comment]
@StalkAlex are you sure you are using [Babun](http://babun.github.io/)?

It seems like your system is trying to use a `cygwin` path (`/cygdrive/c/...`) from inside a Windows path (`C:/Program Files/Git/...`). 

It looks like if you were running some Git bash or something similar. **babun-docker** won't work in that case.

The normal process would be to:

* Install Docker Toolbox
* Run the Docker Terminal (that's a Git bash) once, to make sure everything is installed and working correctly
* Install Babun
* Install **babun-docker**

If you are running `docker-machine` directly with another Hypervisor or something similar (as it seems like since you mention vSphere), you should first make sure that everything works "normally" before installing babun-docker in whatever configuration you have.

* Then install Babun.
* Then make sure everything works with `docker-machine` "normally" inside Babun.
* Then install **babun-docker**.
* Then configure **babun-docker** accordingly with your environment, you probably don't want it to try to set-up VirtualBox (Docker Toolbox) volumes, and you probably want to configure `docker-machine` with a custom VM name, etc. Follow the configuration guide: https://github.com/tiangolo/babun-docker#configurations

**Comment by StalkAlex** [comment]
> @StalkAlex are you sure you are using Babun?

Yes, quite sure, I'm starting it by open Babun icon and it definetely showes babun with all those checks and so on.

> It looks like if you were running some Git bash or something similar. babun-docker won't work in that case.

Docker toolbox exactly uses git bash.

> The normal process would be to:

In my case I'm using Babun for several months and couple days ago I installed Docker toolbox, then Babun-docker. Could this be a reason? 

> If you are running docker-machine directly with another Hypervisor or something similar (as it seems like since you mention vSphere), you should first make sure that everything works "normally" before installing babun-docker in whatever configuration you have.

Everything worked before installing Babun-docker. Now I've moved to BashOnWindows, Docker toolbox works without extra effort in there. And I'm too lazy to reinstall everything in correct order:)

**Comment by tiangolo** [comment]
OK, I'm glad you solved your problem :+1: . I will then close this issue now.

**Comment by StalkAlex** [comment]
Ok, no problem. But real problem still exists.

**Comment by tiangolo** [comment]
@StalkAlex I don't know your configuration (with vSphere, etc). I can't replicate your environment, and no one else seems to have exactly your same problem, so I have no way to find out, debug and fix what could be wrong (assuming that something is actually wrong).

And as this seems to be quite a special case (with however it is that you have your environment set up), I can't do much until you or someone with your exact same environment can test and debug the issue.

**Comment by StalkAlex** [comment]
Ok, thank you! I'll update this issue in case I find out something new.
